### ISSUE TITLE
Switch from CommandInterfaces to individual Commands

### ISSUE THREAD

**Issue by MxBlu** [MxBlu/bot-framework#2]
Each "Command" should provide aliases and a handle function. Should split up the code base a bit.

**Comment by wongcoder** [comment]
k

**Comment by MxBlu** [comment]
I'm thinking similar to the how I implemented it recently in the Go version:
https://github.com/tr4656/weeb-bot-go/blob/c743de688577e44e810cf9071d7529ffb7c9b03f/framework/bot/defaultcommands/helpcommand.go
